apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: tickethub
    tier: backend
spec:
  type: NodePort
  selector:
    app: tickethub
    tier: backend
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001