namePrefix: prod-
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- ingress-alb.yaml
commonLabels:
  app: tickethub
  tier: frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization