apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-000e160e18cb51473,subnet-010fe1609e5857c5d
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-backend-service
            port:
              number: 9001