namePrefix: prod-
resources:
- backend-deployment.yaml
- backend-service.yaml
- internal-alb.yaml
commonLabels:
  app: tickethub
  tier: backend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization